# Generated by Django 3.2 on 2021-04-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_groceryitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='owner',
        ),
    ]
